In [2]:
import torch

a = torch.tensor([1, 2, 3, 4], dtype = torch.float)
print(torch.softmax(a, dim=0))


a = torch.unsqueeze(a, dim=1)
m = torch.nn.Softmax(dim=1)
print(a)
print(m(a))

a = torch.squeeze(a, dim=1)
m = torch.nn.Softmax(dim=0)
print(a)
print(m(a))

tensor([0.0321, 0.0871, 0.2369, 0.6439])
tensor([[1.],
        [2.],
        [3.],
        [4.]])
tensor([[1.],
        [1.],
        [1.],
        [1.]])
tensor([1., 2., 3., 4.])
tensor([0.0321, 0.0871, 0.2369, 0.6439])


In [47]:
import torch

a = torch.randn((32, 5))
print(a.size())
print(torch.softmax(a, dim=1))

torch.Size([32, 5])
tensor([[0.2797, 0.1261, 0.1769, 0.3503, 0.0670],
        [0.2544, 0.2684, 0.0621, 0.0433, 0.3719],
        [0.5148, 0.1591, 0.0350, 0.0420, 0.2490],
        [0.3425, 0.2680, 0.1393, 0.1411, 0.1091],
        [0.4370, 0.0301, 0.2428, 0.1009, 0.1892],
        [0.5858, 0.1862, 0.0780, 0.0222, 0.1279],
        [0.1838, 0.0161, 0.0608, 0.6250, 0.1143],
        [0.2588, 0.0906, 0.2599, 0.3393, 0.0514],
        [0.4596, 0.2959, 0.0300, 0.1644, 0.0501],
        [0.1925, 0.2015, 0.0228, 0.2341, 0.3492],
        [0.2926, 0.1672, 0.1070, 0.2004, 0.2328],
        [0.3492, 0.1506, 0.2867, 0.0491, 0.1643],
        [0.0202, 0.4887, 0.0199, 0.0511, 0.4201],
        [0.2694, 0.5388, 0.0358, 0.1367, 0.0194],
        [0.1460, 0.2945, 0.1663, 0.2835, 0.1097],
        [0.0211, 0.0954, 0.5828, 0.0878, 0.2129],
        [0.3008, 0.2293, 0.2661, 0.1716, 0.0322],
        [0.4209, 0.4067, 0.0599, 0.0855, 0.0271],
        [0.2152, 0.0554, 0.3402, 0.2077, 0.1816],
        [0.2258, 0.0622, 0.020

In [6]:
import torch

A = torch.zeros(2, 3, 4)
B = torch.ones(2, 3, 1)

C = torch.cat([A, B], -1)
print(C.shape)
print(C)

torch.Size([2, 3, 5])
tensor([[[0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 1.]],

        [[0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 1.]]])


In [9]:
import torch.nn as nn

m = nn.AdaptiveAvgPool2d((1,1))
input = torch.randn(32, 64, 8, 9)
output = m(input)
print(output.shape)
# target output size of 7x7 (square)
m = nn.AdaptiveAvgPool2d(7)
input = torch.randn(1, 64, 10, 9)
output = m(input)
print(output.shape)

torch.Size([32, 64, 1, 1])
torch.Size([1, 64, 7, 7])


In [7]:
import torch.nn as nn

a = torch.zeros(2, 3, 4, 5)
nn.init.kaiming_normal_(a, mode='fan_out', nonlinearity='relu')
print(a.fan_out)

AttributeError: 'Tensor' object has no attribute 'fan_out'