In [3]:
from __future__ import print_function
import torch
import numpy as np

In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[9.0919e-39, 8.9082e-39, 9.2755e-39],
        [8.4490e-39, 1.0194e-38, 9.0919e-39],
        [8.4490e-39, 1.0745e-38, 1.0102e-38],
        [9.6429e-39, 8.9082e-39, 9.6429e-39],
        [1.0102e-38, 9.3673e-39, 9.8265e-39]])


In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1610, 0.3348, 0.9130],
        [0.1299, 0.6322, 0.5556],
        [0.1420, 0.5830, 0.8455],
        [0.7507, 0.1554, 0.0799],
        [0.4318, 0.2021, 0.0160]])


In [6]:
x = torch.zeros(5, 3, dtype = torch.float64)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [7]:
x = torch.tensor(np.arange(12))
print(x)
x = torch.tensor([1, 2])
print(x)
x = torch.tensor(1.)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=torch.int32)
tensor([1, 2])
tensor(1.)


In [8]:
x = x.new_ones(5, 3)
print(x)

x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[-0.5325,  0.4142,  0.3543],
        [-1.1940, -2.5324, -2.0227],
        [-1.2842,  1.6160, -0.5567],
        [-1.7320, -0.9830, -0.2745],
        [-0.1649, -0.9282,  1.5012]])


In [9]:
print(x.size())

torch.Size([5, 3])


In [10]:
y = torch.rand(5, 3)
print(x)
print(x.add(y))
print(x)

tensor([[-0.5325,  0.4142,  0.3543],
        [-1.1940, -2.5324, -2.0227],
        [-1.2842,  1.6160, -0.5567],
        [-1.7320, -0.9830, -0.2745],
        [-0.1649, -0.9282,  1.5012]])
tensor([[-0.0188,  0.9581,  0.7263],
        [-0.4798, -2.1716, -1.2635],
        [-1.0711,  1.8719,  0.0115],
        [-1.6489, -0.7230,  0.1634],
        [ 0.4737, -0.3231,  1.9193]])
tensor([[-0.5325,  0.4142,  0.3543],
        [-1.1940, -2.5324, -2.0227],
        [-1.2842,  1.6160, -0.5567],
        [-1.7320, -0.9830, -0.2745],
        [-0.1649, -0.9282,  1.5012]])


In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

tensor([[-0.0188,  0.9581,  0.7263],
        [-0.4798, -2.1716, -1.2635],
        [-1.0711,  1.8719,  0.0115],
        [-1.6489, -0.7230,  0.1634],
        [ 0.4737, -0.3231,  1.9193]])


In [12]:
x = torch.randn(4, 4)
print(x)
y = x.view(16)
print(y)
z = x.view(2, -1)
print(z)

tensor([[-1.0128,  0.4708, -1.2474,  0.4702],
        [ 0.3325, -0.3114,  1.0991,  0.8829],
        [-1.6745, -2.2039,  0.2103,  0.1087],
        [ 0.8229,  0.2399, -0.6515,  1.6143]])
tensor([-1.0128,  0.4708, -1.2474,  0.4702,  0.3325, -0.3114,  1.0991,  0.8829,
        -1.6745, -2.2039,  0.2103,  0.1087,  0.8229,  0.2399, -0.6515,  1.6143])
tensor([[-1.0128,  0.4708, -1.2474,  0.4702,  0.3325, -0.3114,  1.0991,  0.8829],
        [-1.6745, -2.2039,  0.2103,  0.1087,  0.8229,  0.2399, -0.6515,  1.6143]])


In [13]:
x = torch.randn(2, 3)
print(x)
print(x[1, 1].item())

tensor([[ 0.2844, -0.0453,  0.3944],
        [ 0.7522,  1.8918,  2.1644]])
1.891800045967102


In [14]:
a = torch.ones(4, 4)
print(a)
b = a.numpy()
print(b)
print(type(b))


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.ndarray'>


In [15]:
a.add_(1)
print(a)
print(b)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [16]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [17]:
import torch
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[1.2844, 0.9547, 1.3944],
        [1.7522, 2.8918, 3.1644]], device='cuda:0')
tensor([[1.2844, 0.9547, 1.3944],
        [1.7522, 2.8918, 3.1644]], dtype=torch.float64)


In [18]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a)
print(a.requires_grad)

b = (a * a).sum()
print(b)
print(b.grad_fn)

False
tensor([[-6.3716,  6.8664],
        [11.4320, -1.6055]], requires_grad=True)
True
tensor(221.0117, grad_fn=<SumBackward0>)


In [19]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.requires_grad)

y = x + 2
print(y)
print(y.requires_grad)

z = y * y * 3
print(z)
print(z.requires_grad)

mean = z.mean()
print(mean)
print(mean.requires_grad)

mean.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
True
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
True
tensor(27., grad_fn=<MeanBackward0>)
True
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [20]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x * 2
# 默认二范数
while y.data.norm() < 1000:
    y = y * 2

print(y)

z = y.mean()
print(z)

tensor([-1.1918,  0.1384, -0.0548], requires_grad=True)
tensor([-1220.3728,   141.7573,   -56.1410], grad_fn=<MulBackward0>)
tensor(-378.2522, grad_fn=<MeanBackward0>)


In [21]:
print(x)
v = torch.tensor([0.1, 1.0, 0.001], dtype = torch.float)
# y.backward(v)
# print(x.grad)

z.backward()
print(x.grad)

tensor([-1.1918,  0.1384, -0.0548], requires_grad=True)
tensor([341.3333, 341.3333, 341.3333])


In [22]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [23]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x == y)
print(x.eq(y).all())

True
False
tensor([True, True, True])
tensor(True)


In [24]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class NeuralNetwork(nn.Module):

    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)

        self.ff1 = nn.Linear(16 * 6 * 6, 120)
        self.ff2 = nn.Linear(120, 84)
        self.ff3 = nn.Linear(84, 10)

    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)

        x = x.view(-1, self.num_flat_featrues(x))
        x = F.relu(self.ff1(x))
        x = F.relu(self.ff2(x))
        x = self.ff3(x)
        return x
    
    def num_flat_featrues(self, x):
        size = x.size()[1:]
        res = 1
        for s in size:
            res *= s
        return res

In [25]:
net = NeuralNetwork()
print(net)

params = list(net.parameters())
print(params.__len__())
for p in params:
    print(p.size())

NeuralNetwork(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (ff1): Linear(in_features=576, out_features=120, bias=True)
  (ff2): Linear(in_features=120, out_features=84, bias=True)
  (ff3): Linear(in_features=84, out_features=10, bias=True)
)
10
torch.Size([6, 1, 3, 3])
torch.Size([6])
torch.Size([16, 6, 3, 3])
torch.Size([16])
torch.Size([120, 576])
torch.Size([120])
torch.Size([84, 120])
torch.Size([84])
torch.Size([10, 84])
torch.Size([10])


In [26]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[ 0.0031, -0.0447,  0.0378,  0.0104,  0.1341,  0.1053, -0.1441,  0.0166,
         -0.0637, -0.0173]], grad_fn=<AddmmBackward>)


In [27]:
net.zero_grad()
out.backward(torch.randn(1, 10))

In [28]:
output = net(input)
target = torch.randn(10)  # a dummy target, for example
target = target.view(1, -1)  # make it the same shape as output
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor(1.0274, grad_fn=<MseLossBackward>)


In [29]:
print(loss.grad_fn)  # MSELoss
print(loss.grad_fn.next_functions[0][0])  # Linear
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])  # ReLU

In [30]:
net.zero_grad()     # zeroes the gradient buffers of all parameters

print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad after backward
tensor([ 3.4551e-03, -7.1575e-03, -2.2623e-02,  2.0968e-02, -6.1795e-05,
         4.6398e-03])


In [31]:
lr = 1
print(list(net.parameters())[0].data)


for f in net.parameters():
    f.data.sub_(f.grad.data * lr)

print(list(net.parameters())[0].data)

tensor([[[[-0.2079, -0.1239, -0.2083],
          [-0.1698, -0.1789, -0.1383],
          [ 0.2377, -0.2284, -0.2257]]],


        [[[-0.0301,  0.2564, -0.1563],
          [ 0.0481, -0.1358,  0.0810],
          [ 0.0996,  0.0354,  0.1841]]],


        [[[-0.2912,  0.2055, -0.2457],
          [ 0.0550,  0.1501, -0.1054],
          [ 0.1912,  0.2574, -0.1901]]],


        [[[-0.1409,  0.2050, -0.1754],
          [ 0.1821,  0.1946,  0.2559],
          [-0.0241, -0.0960, -0.0494]]],


        [[[ 0.3306,  0.3072,  0.2763],
          [-0.2402, -0.2471,  0.2115],
          [ 0.1913, -0.2049, -0.1863]]],


        [[[ 0.0630,  0.0084, -0.2275],
          [ 0.2480,  0.1766,  0.2324],
          [ 0.1345,  0.0245, -0.0695]]]])
tensor([[[[-0.2095, -0.1137, -0.2211],
          [-0.1672, -0.1863, -0.1404],
          [ 0.2364, -0.2223, -0.2086]]],


        [[[-0.0174,  0.2728, -0.1637],
          [ 0.0730, -0.1355,  0.1000],
          [ 0.1156,  0.0245,  0.1929]]],


        [[[-0.3079,  0.2135, -0.2

In [32]:
import torch.optim as optim

optimizer = optim.SGD(net.parameters(), lr=0.01)

optimizer.zero_grad()
output = net(input)
loss = criterion(output, target)
loss.backward()

optimizer.step()