In [221]:
from __future__ import print_function
import torch
import numpy as np

In [222]:
x = torch.empty(5, 3)
print(x)

tensor([[1.0653e-38, 1.0194e-38, 8.4490e-39],
        [9.6429e-39, 8.4490e-39, 9.6429e-39],
        [9.2755e-39, 1.0286e-38, 9.0919e-39],
        [8.9082e-39, 9.2755e-39, 8.4490e-39],
        [1.0194e-38, 9.0919e-39, 8.4490e-39]])


In [223]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0549, 0.0480, 0.5447],
        [0.8441, 0.5198, 0.0073],
        [0.8776, 0.5161, 0.5265],
        [0.4600, 0.7444, 0.3639],
        [0.3632, 0.0863, 0.3706]])


In [224]:
x = torch.zeros(5, 3, dtype = torch.float64)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [225]:
x = torch.tensor(np.arange(12))
print(x)
x = torch.tensor([1, 2])
print(x)
x = torch.tensor(1.)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=torch.int32)
tensor([1, 2])
tensor(1.)


In [226]:
x = x.new_ones(5, 3)
print(x)

x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 0.8543, -0.3033,  1.3905],
        [ 0.5786, -0.1102,  0.2065],
        [-0.7074,  0.6953, -1.8976],
        [ 0.1590, -0.8507,  1.5624],
        [ 1.2459,  0.8895, -0.7093]])


In [227]:
print(x.size())

torch.Size([5, 3])


In [228]:
y = torch.rand(5, 3)
print(x)
print(x.add(y))
print(x)

tensor([[ 0.8543, -0.3033,  1.3905],
        [ 0.5786, -0.1102,  0.2065],
        [-0.7074,  0.6953, -1.8976],
        [ 0.1590, -0.8507,  1.5624],
        [ 1.2459,  0.8895, -0.7093]])
tensor([[ 1.2500,  0.3228,  1.5599],
        [ 1.0046,  0.2774,  0.9113],
        [-0.5697,  1.2437, -1.3235],
        [ 0.4213, -0.6352,  1.7264],
        [ 2.2224,  1.0408, -0.0348]])
tensor([[ 0.8543, -0.3033,  1.3905],
        [ 0.5786, -0.1102,  0.2065],
        [-0.7074,  0.6953, -1.8976],
        [ 0.1590, -0.8507,  1.5624],
        [ 1.2459,  0.8895, -0.7093]])


In [229]:
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

tensor([[ 1.2500,  0.3228,  1.5599],
        [ 1.0046,  0.2774,  0.9113],
        [-0.5697,  1.2437, -1.3235],
        [ 0.4213, -0.6352,  1.7264],
        [ 2.2224,  1.0408, -0.0348]])


In [230]:
x = torch.randn(4, 4)
print(x)
y = x.view(16)
print(y)
z = x.view(2, -1)
print(z)

tensor([[ 0.2751, -2.5139,  1.4946, -0.7663],
        [-1.3347, -2.0894,  1.9610, -1.8249],
        [ 1.5732, -1.0853,  1.1302, -1.3456],
        [-0.0648,  0.4415, -1.3854, -0.2662]])
tensor([ 0.2751, -2.5139,  1.4946, -0.7663, -1.3347, -2.0894,  1.9610, -1.8249,
         1.5732, -1.0853,  1.1302, -1.3456, -0.0648,  0.4415, -1.3854, -0.2662])
tensor([[ 0.2751, -2.5139,  1.4946, -0.7663, -1.3347, -2.0894,  1.9610, -1.8249],
        [ 1.5732, -1.0853,  1.1302, -1.3456, -0.0648,  0.4415, -1.3854, -0.2662]])


In [231]:
x = torch.randn(2, 3)
print(x)
print(x[1, 1].item())

tensor([[-0.4267,  1.5365,  1.0220],
        [-0.2331, -0.3418, -0.4315]])
-0.34176233410835266


In [232]:
a = torch.ones(4, 4)
print(a)
b = a.numpy()
print(b)
print(type(b))


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.ndarray'>


In [233]:
a.add_(1)
print(a)
print(b)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [234]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [235]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[0.5733, 2.5365, 2.0220],
        [0.7669, 0.6582, 0.5685]], device='cuda:0')
tensor([[0.5733, 2.5365, 2.0220],
        [0.7669, 0.6582, 0.5685]], dtype=torch.float64)


In [236]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a)
print(a.requires_grad)

b = (a * a).sum()
print(b)
print(b.grad_fn)

False
tensor([[ 0.2729,  0.7477],
        [-4.1483,  5.0544]], requires_grad=True)
True
tensor(43.3887, grad_fn=<SumBackward0>)


In [237]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.requires_grad)

y = x + 2
print(y)
print(y.requires_grad)

z = y * y * 3
print(z)
print(z.requires_grad)

mean = z.mean()
print(mean)
print(mean.requires_grad)

mean.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
True
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
True
tensor(27., grad_fn=<MeanBackward0>)
True
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [238]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x * 2
# 默认二范数
while y.data.norm() < 1000:
    y = y * 2

print(y)

z = y.mean()
print(z)

tensor([ 0.1881, -0.9697, -0.5909], requires_grad=True)
tensor([ 192.6114, -992.9422, -605.0761], grad_fn=<MulBackward0>)
tensor(-468.4690, grad_fn=<MeanBackward0>)


In [239]:
print(x)
v = torch.tensor([0.1, 1.0, 0.001], dtype = torch.float)
# y.backward(v)
# print(x.grad)

z.backward()
print(x.grad)

tensor([ 0.1881, -0.9697, -0.5909], requires_grad=True)
tensor([341.3333, 341.3333, 341.3333])


In [240]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [241]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x == y)
print(x.eq(y).all())

True
False
tensor([True, True, True])
tensor(True)


In [242]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class NeuralNetwork(nn.Module):

    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)

        self.ff1 = nn.Linear(16 * 6 * 6, 120)
        self.ff2 = nn.Linear(120, 84)
        self.ff3 = nn.Linear(84, 10)

    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)

        x = x.view(-1, self.num_flat_featrues(x))
        x = F.relu(self.ff1(x))
        x = F.relu(self.ff2(x))
        x = self.ff3(x)
        return x
    
    def num_flat_featrues(self, x):
        size = x.size()[1:]
        res = 1
        for s in size:
            res *= s
        return res

In [243]:
net = NeuralNetwork()
print(net)

params = list(net.parameters())
print(params.__len__())
for p in params:
    print(p.size())

NeuralNetwork(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (ff1): Linear(in_features=576, out_features=120, bias=True)
  (ff2): Linear(in_features=120, out_features=84, bias=True)
  (ff3): Linear(in_features=84, out_features=10, bias=True)
)
10
torch.Size([6, 1, 3, 3])
torch.Size([6])
torch.Size([16, 6, 3, 3])
torch.Size([16])
torch.Size([120, 576])
torch.Size([120])
torch.Size([84, 120])
torch.Size([84])
torch.Size([10, 84])
torch.Size([10])


In [253]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[-0.0959,  0.0837, -0.0397,  0.0508,  0.0516, -0.0667, -0.0193, -0.0601,
          0.0252, -0.0099]], grad_fn=<AddmmBackward>)


In [254]:
net.zero_grad()
out.backward(torch.randn(1, 10))

In [294]:
output = net(input)
target = torch.randn(10)  # a dummy target, for example
target = target.view(1, -1)  # make it the same shape as output
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor(0.6198, grad_fn=<MseLossBackward>)


In [267]:
print(loss.grad_fn)  # MSELoss
print(loss.grad_fn.next_functions[0][0])  # Linear
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])  # ReLU

In [286]:
net.zero_grad()     # zeroes the gradient buffers of all parameters

print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad after backward
tensor([ 0.0078, -0.0107,  0.0156,  0.0109, -0.0041, -0.0354])


In [297]:
lr = 1
print(list(net.parameters())[0].data)


for f in net.parameters():
    f.data.sub_(f.grad.data * lr)

print(list(net.parameters())[0].data)

tensor([[[[ 0.0823,  0.2070, -0.2050],
          [ 0.1239, -0.2487,  0.0959],
          [-0.2580, -0.1075, -0.0326]]],


        [[[ 0.3119, -0.2846,  0.1717],
          [ 0.2668, -0.2483,  0.0684],
          [-0.1244,  0.0320,  0.3458]]],


        [[[-0.0043, -0.0786, -0.1916],
          [ 0.2110,  0.2002,  0.1834],
          [ 0.2470, -0.1661, -0.2878]]],


        [[[-0.0544, -0.3253, -0.3291],
          [-0.2136, -0.1472,  0.2057],
          [ 0.0489,  0.1800,  0.3317]]],


        [[[-0.2338, -0.2033,  0.1565],
          [ 0.0554,  0.2191,  0.2251],
          [-0.3129,  0.2001,  0.0947]]],


        [[[ 0.0800, -0.0114,  0.1360],
          [-0.1003, -0.0791,  0.2523],
          [ 0.0248,  0.0159,  0.3524]]]])
tensor([[[[ 0.0778,  0.2105, -0.2027],
          [ 0.1147, -0.2271,  0.1038],
          [-0.2636, -0.0900, -0.0329]]],


        [[[ 0.3161, -0.2828,  0.1615],
          [ 0.2819, -0.2262,  0.0564],
          [-0.1326,  0.0418,  0.3630]]],


        [[[-0.0023, -0.0792, -0.1

In [298]:
import torch.optim as optim

optimizer = optim.SGD(net.parameters(), lr=0.01)

optimizer.zero_grad()
output = net(input)
loss = criterion(output, target)
loss.backward()

optimizer.step()