In [1]:
from __future__ import print_function
import torch
import numpy as np

In [2]:
# 未初始化的tensor
x = torch.empty(5, 3)
print(x)

tensor([[1.5072e-09, 7.3428e-43, 1.5072e-09],
        [7.3428e-43, 1.5073e-09, 7.3428e-43],
        [1.5073e-09, 7.3428e-43, 1.5072e-09],
        [7.3428e-43, 1.5072e-09, 7.3428e-43],
        [1.5072e-09, 7.3428e-43, 1.5072e-09]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0179, 0.5701, 0.4657],
        [0.0059, 0.5487, 0.1753],
        [0.7605, 0.7197, 0.1914],
        [0.9889, 0.4721, 0.3230],
        [0.5128, 0.3179, 0.0568]])


In [4]:
x = torch.zeros(5, 3, dtype = torch.float64)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [5]:
x = torch.tensor(np.arange(12))
print(x)
x = torch.tensor([1, 2])
print(x)
x = torch.tensor(1.)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=torch.int32)
tensor([1, 2])
tensor(1.)


In [6]:
# 基于x返回一个具有相同类型与同样设备的tensor
x = x.new_ones(5, 3)
print(x)

x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[-0.8730,  0.5166, -0.0898],
        [-0.7214,  0.8792, -0.2893],
        [ 1.8547,  2.4534,  1.5781],
        [-0.4748,  1.1745,  0.1840],
        [-0.0272, -0.5665,  0.4253]])


In [7]:
print(x.size())
print(x.size(0))

torch.Size([5, 3])
5


In [8]:
y = torch.rand(5, 3)
print(x)
print(x.add(y))
print(x)

tensor([[-0.8730,  0.5166, -0.0898],
        [-0.7214,  0.8792, -0.2893],
        [ 1.8547,  2.4534,  1.5781],
        [-0.4748,  1.1745,  0.1840],
        [-0.0272, -0.5665,  0.4253]])
tensor([[-0.1411,  0.7712,  0.8229],
        [ 0.1132,  1.0495,  0.2500],
        [ 1.8597,  3.2619,  1.5954],
        [ 0.3823,  1.6825,  1.0051],
        [ 0.8025, -0.4655,  0.8510]])
tensor([[-0.8730,  0.5166, -0.0898],
        [-0.7214,  0.8792, -0.2893],
        [ 1.8547,  2.4534,  1.5781],
        [-0.4748,  1.1745,  0.1840],
        [-0.0272, -0.5665,  0.4253]])


In [9]:
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

tensor([[-0.1411,  0.7712,  0.8229],
        [ 0.1132,  1.0495,  0.2500],
        [ 1.8597,  3.2619,  1.5954],
        [ 0.3823,  1.6825,  1.0051],
        [ 0.8025, -0.4655,  0.8510]])


In [10]:
x = torch.randn(4, 4)
print(x)
y = x.view(16)
print(y)
z = x.view(2, -1)
print(z)

a=torch.Tensor([[[1,2,3],[4,5,6]]])
print(a.view(3,2))

tensor([[ 0.4956,  1.2802, -0.8890, -1.4909],
        [ 0.3764,  1.7616,  0.7685,  1.5485],
        [-0.9623, -0.0247, -0.5112,  0.1391],
        [-1.2642,  2.3014, -0.6450,  1.2704]])
tensor([ 0.4956,  1.2802, -0.8890, -1.4909,  0.3764,  1.7616,  0.7685,  1.5485,
        -0.9623, -0.0247, -0.5112,  0.1391, -1.2642,  2.3014, -0.6450,  1.2704])
tensor([[ 0.4956,  1.2802, -0.8890, -1.4909,  0.3764,  1.7616,  0.7685,  1.5485],
        [-0.9623, -0.0247, -0.5112,  0.1391, -1.2642,  2.3014, -0.6450,  1.2704]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [11]:
x = torch.randn(2, 3)
print(x)
print(x[1, 1].item())

tensor([[-0.4269,  0.0539,  1.1357],
        [ 0.5590,  2.1777, -0.2378]])
2.177673816680908


In [12]:
a = torch.ones(4, 4)
print(a)
b = a.numpy()
print(b)
print(type(b))


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.ndarray'>


In [13]:
print(a)
print(b)
a.add_(1)
print(a)
print(b)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [14]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [15]:
import torch
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[0.5731, 1.0539, 2.1357],
        [1.5590, 3.1777, 0.7622]], device='cuda:0')
tensor([[0.5731, 1.0539, 2.1357],
        [1.5590, 3.1777, 0.7622]], dtype=torch.float64)


In [16]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a)
print(a.requires_grad)

print(a * a)
b = (a * a).sum()
print(b)
print(b.grad_fn)

False
tensor([[-0.0948,  8.0444],
        [-0.3139, -2.7368]], requires_grad=True)
True
tensor([[8.9927e-03, 6.4712e+01],
        [9.8549e-02, 7.4899e+00]], grad_fn=<MulBackward0>)
tensor(72.3096, grad_fn=<SumBackward0>)


In [17]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.requires_grad)

y = x + 2
print(y)
print(y.requires_grad)

z = y * y * 3
print(z)
print(z.requires_grad)

mean = z.mean()
print(mean)
print(mean.requires_grad)

mean.backward()
# print(z.grad)
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
True
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
True
tensor(27., grad_fn=<MeanBackward0>)
True
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [18]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x * 2
print(y)
# 默认二范数
while y.data.norm() < 1000:
    y = 2 * y

print(y)

z = y.mean()
print(z)

tensor([-0.4424, -0.4969, -0.9364], requires_grad=True)
tensor([-0.8847, -0.9937, -1.8729], grad_fn=<MulBackward0>)
tensor([-452.9764, -508.7747, -958.9074], grad_fn=<MulBackward0>)
tensor(-640.2195, grad_fn=<MeanBackward0>)


In [19]:
# v = torch.tensor([0.1, 1.0, 0.001], dtype = torch.float)
# y.backward(v, retain_graph=True)
# y.backward()
z.backward()
print(x.grad)

tensor([341.3333, 341.3333, 341.3333])


In [20]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [21]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

Q = 3*a**3 - b**2

external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])


<img src='向量雅克比积.png' style="zoom: 80%;">

In [34]:
x = torch.rand(5, 5)
y = torch.rand(5, 5)
z = torch.rand((5, 5), requires_grad=True)

a = x + y
print(f"Does `a` require gradients? : {a.requires_grad}")
b = x + z
print(f"Does `b` require gradients?: {b.requires_grad}")

Does `a` require gradients? : False
Does `b` require gradients?: True


In [40]:
from torch import nn, optim
import torchvision

model = torchvision.models.resnet18(pretrained=True)

print(model)
# Freeze all the parameters in the network
for param in model.parameters():
    param.requires_grad = False

# unfrozen by default
model.fc = nn.Linear(512, 10)

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [50]:
print(x.requires_grad)
y = x.detach()
z = x.data
print(y.requires_grad)
print(x == y)
print(id(x))
print(id(y))
print(id(z))
print(x.eq(y).all())

False
False
tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])
2251642702808
2250840335688
2250840297944
tensor(True)


In [23]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class NeuralNetwork(nn.Module):

    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)

        self.ff1 = nn.Linear(16 * 6 * 6, 120)
        self.ff2 = nn.Linear(120, 84)
        self.ff3 = nn.Linear(84, 10)

    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)

        x = x.view(-1, self.num_flat_featrues(x))
        x = F.relu(self.ff1(x))
        x = F.relu(self.ff2(x))
        x = self.ff3(x)
        return x
    
    def num_flat_featrues(self, x):
        size = x.size()[1:]
        res = 1
        for s in size:
            res *= s
        return res

In [24]:
net = NeuralNetwork()
print(net)

params = list(net.parameters())
print(params.__len__())
for p in params:
    print(p.size())

NeuralNetwork(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (ff1): Linear(in_features=576, out_features=120, bias=True)
  (ff2): Linear(in_features=120, out_features=84, bias=True)
  (ff3): Linear(in_features=84, out_features=10, bias=True)
)
10
torch.Size([6, 1, 3, 3])
torch.Size([6])
torch.Size([16, 6, 3, 3])
torch.Size([16])
torch.Size([120, 576])
torch.Size([120])
torch.Size([84, 120])
torch.Size([84])
torch.Size([10, 84])
torch.Size([10])


In [25]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[ 0.0021,  0.0234, -0.1049, -0.1233, -0.1361, -0.0314, -0.0025, -0.1422,
          0.0288, -0.0501]], grad_fn=<AddmmBackward>)


In [26]:
net.zero_grad()
out.backward(torch.randn(1, 10))

In [27]:
output = net(input)
target = torch.randn(10)  # a dummy target, for example
target = target.view(1, -1)  # make it the same shape as output
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor(0.4851, grad_fn=<MseLossBackward>)


In [28]:
print(loss.grad_fn)  # MSELoss
print(loss.grad_fn.next_functions[0][0])  # Linear
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])  # ReLU

In [29]:
net.zero_grad()     # zeroes the gradient buffers of all parameters

print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

# optimizer.step()

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad after backward
tensor([ 0.0003, -0.0014, -0.0099,  0.0093, -0.0055,  0.0070])


In [44]:
lr = 1
print(list(net.parameters())[0].data)
# print(net.parameters())

for f in net.parameters():
    f.data.sub_(f.grad.data * lr)

print(list(net.parameters())[0].data)

tensor([[[[ 8.6246e-02,  1.9947e-02, -3.1505e-02],
          [-1.4553e-01, -8.7981e-02, -1.0204e-01],
          [-2.8210e-02,  3.0955e-01, -2.8297e-01]]],


        [[[-2.6976e-01,  4.2148e-02,  3.2054e-01],
          [ 3.7663e-01,  3.1329e-01, -1.8862e-01],
          [ 1.0169e-01,  8.7619e-02,  2.2490e-01]]],


        [[[ 3.3657e-02,  1.7558e-01,  7.8869e-02],
          [-2.6592e-02,  3.4262e-01,  2.0191e-01],
          [-2.2809e-02,  9.5029e-02, -3.8280e-01]]],


        [[[ 6.2686e-02,  2.2796e-01,  1.6377e-01],
          [-4.3607e-02, -2.7806e-01,  2.5816e-01],
          [-3.4707e-01, -1.3352e-01, -4.3442e-02]]],


        [[[-2.9319e-01, -4.5864e-02, -3.8315e-02],
          [-1.5482e-01, -3.1108e-01, -8.4520e-02],
          [ 2.2495e-01, -6.3066e-02,  1.3796e-02]]],


        [[[ 1.4977e-01, -1.2370e-04, -4.8942e-02],
          [ 3.2611e-01,  1.4503e-03, -2.1540e-01],
          [-1.6851e-01, -1.7100e-02,  8.8259e-02]]]])
tensor([[[[ 0.0792,  0.0209, -0.0282],
          [-0.1467, 

In [31]:
import torch.optim as optim

optimizer = optim.SGD(net.parameters(), lr=0.01)

optimizer.zero_grad()
output = net(input)
loss = criterion(output, target)
loss.backward()

optimizer.step()

In [32]:
import torch

x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)


In [33]:
print('Gradient function for z =',z.grad_fn)
print('Gradient function for loss =', loss.grad_fn)

loss.backward()
# We can only perform gradient calculations using backward once on a given graph, for performance reasons. If we need to do several backward calls on the same graph, we need to pass retain_graph=True to the backward call.
print(w.grad)
print(b.grad)

z = torch.matmul(x, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
loss.backward()
print(w.grad)
print(b.grad) 
# 从结果可以看出 虽然调用了多次backward重新建立了计算图，梯度仍是累加的

# print(z.grad) 
# We can only obtain the grad properties for the leaf nodes of the computational graph, which have requires_grad property set to True. For all other nodes in our graph, gradients will not be available.

# By default, all tensors with requires_grad=True are tracking their computational history and support gradient computation. However, there are some cases when we do not need to do that, for example, when we have trained the model and just want to apply it to some input data, i.e. we only want to do forward computations through the network. We can stop tracking computations by surrounding our computation code with torch.no_grad() block:

z = torch.matmul(x, w)+b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)



# DAGs are dynamic in PyTorch An important thing to note is that the graph is recreated from scratch; after each .backward() call, autograd starts populating a new graph. This is exactly what allows you to use control flow statements in your model; you can change the shape, size and operations at every iteration if needed.

Gradient function for z = <AddBackward0 object at 0x0000020C034D9908>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward object at 0x0000020C034D98C8>
tensor([[0.1997, 0.0099, 0.3071],
        [0.1997, 0.0099, 0.3071],
        [0.1997, 0.0099, 0.3071],
        [0.1997, 0.0099, 0.3071],
        [0.1997, 0.0099, 0.3071]])
tensor([0.1997, 0.0099, 0.3071])
tensor([[0.3994, 0.0197, 0.6142],
        [0.3994, 0.0197, 0.6142],
        [0.3994, 0.0197, 0.6142],
        [0.3994, 0.0197, 0.6142],
        [0.3994, 0.0197, 0.6142]])
tensor([0.3994, 0.0197, 0.6142])
True
False
