In [41]:
from __future__ import print_function
import torch
import numpy as np

In [42]:
x = torch.empty(5, 3)
print(x)

tensor([[1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39],
        [1.0653e-38, 1.0469e-38, 4.2246e-39],
        [1.0378e-38, 9.6429e-39, 9.2755e-39]])


In [43]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5418, 0.4589, 0.7664],
        [0.2448, 0.6692, 0.6986],
        [0.8473, 0.7671, 0.2265],
        [0.1085, 0.9605, 0.3742],
        [0.3550, 0.2158, 0.7821]])


In [44]:
x = torch.zeros(5, 3, dtype = torch.float64)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [65]:
x = torch.tensor(np.arange(12))
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=torch.int32)


In [71]:
x = x.new_ones(5, 3)
print(x)

x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[-0.9754, -1.1602, -0.5728],
        [-0.6959, -0.3994,  2.4481],
        [-2.1447,  1.8039, -0.0451],
        [ 0.0568,  2.0130, -0.6008],
        [-0.2223, -1.5745,  0.6637]])


In [73]:
print(x.size())

torch.Size([5, 3])


In [94]:
y = torch.rand(5, 3)
print(x)
print(x.add(y))
print(x)

tensor([[ 0.2580,  0.0940,  0.2313],
        [ 0.2210,  1.0810,  3.3893],
        [-1.0929,  3.2939,  0.3116],
        [ 0.8926,  2.2718, -0.2256],
        [ 1.0255,  0.1996,  1.0902]])
tensor([[ 0.4604,  0.5059,  1.1349],
        [ 0.3549,  1.4665,  4.0026],
        [-1.0011,  4.1435,  1.1095],
        [ 1.8475,  3.0368,  0.0257],
        [ 1.8426,  0.9081,  1.7286]])
tensor([[ 0.2580,  0.0940,  0.2313],
        [ 0.2210,  1.0810,  3.3893],
        [-1.0929,  3.2939,  0.3116],
        [ 0.8926,  2.2718, -0.2256],
        [ 1.0255,  0.1996,  1.0902]])


In [92]:
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

tensor([[ 0.1890, -0.1807, -0.1415],
        [ 0.4194,  0.6941,  4.0328],
        [-0.9303,  3.5258,  1.0552],
        [ 1.7259,  3.1086,  0.4617],
        [ 0.3097, -0.5542,  1.0601]])


In [104]:
x = torch.randn(4, 4)
print(x)
y = x.view(16)
print(y)
z = x.view(2, -1)
print(z)

tensor([[-1.2816,  1.0171,  0.0701, -1.0332],
        [-1.6413, -0.8156,  0.7131,  1.1496],
        [-0.4205,  0.9336,  0.4796, -2.3778],
        [-0.7002, -0.3703,  1.0539,  1.0119]])
tensor([-1.2816,  1.0171,  0.0701, -1.0332, -1.6413, -0.8156,  0.7131,  1.1496,
        -0.4205,  0.9336,  0.4796, -2.3778, -0.7002, -0.3703,  1.0539,  1.0119])
tensor([[-1.2816,  1.0171,  0.0701, -1.0332, -1.6413, -0.8156,  0.7131,  1.1496],
        [-0.4205,  0.9336,  0.4796, -2.3778, -0.7002, -0.3703,  1.0539,  1.0119]])


In [112]:
x = torch.randn(2, 3)
print(x)
print(x[1, 1].item())

tensor([[-0.4397,  0.2027, -1.4224],
        [ 0.2630,  0.2787, -0.5654]])
0.2787317931652069


In [125]:
a = torch.ones(4, 4)
print(a)
b = a.numpy()
print(b)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [126]:
a.add_(1)
print(a)
print(b)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [129]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [131]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[ 0.5603,  1.2027, -0.4224],
        [ 1.2630,  1.2787,  0.4346]], device='cuda:0')
tensor([[ 0.5603,  1.2027, -0.4224],
        [ 1.2630,  1.2787,  0.4346]], dtype=torch.float64)


In [132]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
