In [1]:
# torch.Tensor.unsqueeze(dim)
# 插入维度1在指定dim上
# 同torch.unsqueeze(input, dim) → Tensor
import torch

x = torch.tensor([1, 2, 3, 4])
print(x.unsqueeze(0))
print(x.unsqueeze(1))

tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


In [2]:
# torch.Tensor.contiguous(memory_format=torch.contiguous_format)
# view 操作依赖于内存是连续的

import torch
x = torch.ones(10, 10)
print(x.is_contiguous())  # True
print(x.view(5, -1).is_contiguous()) # True
print(x.view(2, -1).transpose(0, 1).is_contiguous()) # False
print(x.transpose(0, 1).is_contiguous())  # False
print(x.transpose(0, 1).contiguous().is_contiguous())  # True

True
True
False
False
True


In [5]:
# torch.nn.Module.register_buffer
# register_buffer(name: str, tensor: Optional[torch.Tensor], persistent: bool = True) → None
# Buffers can be accessed as attributes using given names.

# torch.nn.Module.register_buffer('running_mean', torch.zeros(num_features))

NameError: name 'num_features' is not defined

In [24]:
# torch.nn.Module.parameters

from torch.nn import Module

model = torch.nn.Linear(20, 30)
for param in model.parameters():
    print(type(param), param.size())

vec = torch.randn((10, 20))
vec1 = vec[0, :]

output = model(vec)
print(output)
print(output.size())

output = model(vec1)
print(output)
print(output.size())

<class 'torch.nn.parameter.Parameter'> torch.Size([30, 20])
<class 'torch.nn.parameter.Parameter'> torch.Size([30])
tensor([[-5.6082e-01,  2.6110e-01, -1.3870e+00, -4.6757e-01, -6.9922e-01,
         -4.9431e-01, -2.9007e-01, -5.4331e-04, -5.8607e-01, -9.7069e-01,
         -5.4193e-01, -9.1854e-01, -5.4605e-01,  5.5389e-01, -1.3397e-01,
         -1.7871e-01,  2.3373e-01, -3.5868e-01, -1.1650e-01,  1.6038e-01,
          6.6730e-01, -2.2994e-01, -1.0970e-01,  1.4902e+00,  3.7058e-02,
          2.6090e-01, -5.8366e-01,  5.0596e-01,  3.4243e-01, -6.3906e-01],
        [-8.8587e-01,  1.3255e+00, -5.6382e-01,  2.6223e-01,  2.2571e-02,
          3.2612e-01, -5.8976e-01, -5.7534e-03, -1.0274e+00, -9.7454e-02,
         -3.5350e-01, -3.7134e-01,  9.0781e-01,  1.3150e+00, -6.9298e-01,
          6.4488e-01,  2.0093e-01, -6.0642e-01,  1.0707e+00, -4.4424e-01,
         -4.2605e-01, -1.2291e+00,  4.3234e-01, -2.1253e-01, -8.2090e-01,
          8.9539e-01,  2.1255e-01,  5.9120e-01, -5.7845e-02, -4.9749e

In [27]:
# torch.max(input, dim, keepdim)

a = torch.randn(2, 3, 2)
print(a)
print(torch.max(a, 1))
print(torch.max(a, 0))

tensor([[[ 1.1644, -0.9384],
         [-1.0856,  0.3334],
         [-1.2582,  0.7507]],

        [[-1.6556,  1.3005],
         [-1.8899,  0.8326],
         [ 0.5181, -2.3465]]])
torch.return_types.max(
values=tensor([[1.1644, 0.7507],
        [0.5181, 1.3005]]),
indices=tensor([[0, 2],
        [2, 0]]))
torch.return_types.max(
values=tensor([[ 1.1644,  1.3005],
        [-1.0856,  0.8326],
        [ 0.5181,  0.7507]]),
indices=tensor([[0, 1],
        [0, 1],
        [1, 0]]))
