In [1]:
# torch.Tensor.unsqueeze(dim)
# 插入维度1在指定dim上
# 同torch.unsqueeze(input, dim) → Tensor
import torch

x = torch.tensor([[[1, 2, 3, 4]]])
print(x.unsqueeze(1).unsqueeze(1).shape)
print(x.unsqueeze(0))
print()

# squeeze 消去dim==1的
x = torch.zeros(2, 1, 2, 1, 2)
print(x.size())
print(torch.squeeze(x).size())
print(torch.squeeze(x, 0).size())
print(torch.squeeze(x, 1).size())

torch.Size([1, 1, 1, 1, 4])
tensor([[[[1, 2, 3, 4]]]])

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 1, 2])


In [2]:
# torch.Tensor.contiguous(memory_format=torch.contiguous_format)
# Returns a contiguous in memory tensor containing the same data as self tensor. If self tensor is already in the specified memory format, this function returns the self tensor.
# view 操作依赖于内存是连续的

import torch
x = torch.ones(10, 10)
print(x.is_contiguous())  # True
print(x.view(5, -1).is_contiguous()) # True
print(x.view(2, -1).transpose(0, 1).is_contiguous()) # False
print(x.transpose(0, 1).is_contiguous())  # False
print(x.transpose(0, 1).contiguous().is_contiguous())  # True

True
True
False
False
True


In [3]:
# torch.nn.Module.register_buffer
# register_buffer(name: str, tensor: Optional[torch.Tensor], persistent: bool = True) → None
# Buffers can be accessed as attributes using given names.

# torch.nn.Module.register_buffer('running_mean', torch.zeros(num_features))

In [4]:
# torch.nn.Module.parameters

from torch.nn import Module

model = torch.nn.Linear(20, 30)
for param in model.parameters():
    print(type(param), param.size())

vec = torch.randn((10, 20))
vec1 = vec[0, :]

output = model(vec)
print(output)
print(output.size())

output = model(vec1)
print(output)
print(output.size())

<class 'torch.nn.parameter.Parameter'> torch.Size([30, 20])
<class 'torch.nn.parameter.Parameter'> torch.Size([30])
tensor([[ 5.6463e-02, -2.0401e-01, -1.5066e-01, -1.5367e-01,  9.4107e-01,
          7.7045e-02,  6.3558e-01,  4.2444e-01, -2.0648e-01,  1.5113e+00,
          5.0002e-02, -6.7403e-02,  1.0063e+00, -4.8090e-01,  1.0751e-01,
          6.6591e-01, -1.1008e-01,  7.8176e-01, -4.5790e-01,  7.9351e-01,
         -8.5202e-01,  2.3129e-01,  5.6759e-01, -2.3940e-01, -8.3733e-01,
         -5.4415e-01, -5.2467e-01,  1.4409e-02,  3.3837e-01,  1.4605e-01],
        [ 4.8078e-02,  1.4130e-03,  9.5987e-01, -3.8910e-01, -8.7307e-02,
         -7.1647e-01, -1.0594e+00,  3.2038e-01, -8.4332e-01,  3.3733e-01,
          1.3254e-01, -1.0435e+00, -5.9416e-01, -2.5477e-01,  1.0352e+00,
          4.7976e-01, -9.0939e-01, -2.8600e-01,  9.9014e-01, -5.1235e-02,
         -2.1319e+00,  7.8916e-02, -6.5708e-01,  5.7470e-01, -6.3461e-01,
          4.1828e-02, -1.0421e+00,  1.0265e+00, -4.1915e-01, -1.6266e

In [6]:
# torch.max(input, dim, keepdim)

a = torch.randn(2, 3, 2)
print(a)
print(torch.max(a, 1))
print(torch.max(a, 0))

tensor([[[-2.7287,  0.5007],
         [ 0.3005,  0.3204],
         [-0.3785,  0.5644]],

        [[-0.6960,  0.8874],
         [-0.6072,  1.0363],
         [-0.1862,  1.3412]]])
torch.return_types.max(
values=tensor([[ 0.3005,  0.5644],
        [-0.1862,  1.3412]]),
indices=tensor([[1, 2],
        [2, 2]]))
torch.return_types.max(
values=tensor([[-0.6960,  0.8874],
        [ 0.3005,  1.0363],
        [-0.1862,  1.3412]]),
indices=tensor([[1, 1],
        [0, 1],
        [1, 1]]))


In [13]:
# transpose
a = torch.randn(2, 3, 2)
print(a)
b = a.transpose(0, 1)
print(b)

print(a[0][1][0])
print(b[1][0][0])
print(b[2][1][0])
print(a[1][2][0])

tensor([[[ 1.0698, -1.2744],
         [ 0.1123, -1.2028],
         [-1.1492, -0.0476]],

        [[ 0.8291,  0.0046],
         [-0.0686, -1.4995],
         [-0.5092, -0.6035]]])
tensor([[[ 1.0698, -1.2744],
         [ 0.8291,  0.0046]],

        [[ 0.1123, -1.2028],
         [-0.0686, -1.4995]],

        [[-1.1492, -0.0476],
         [-0.5092, -0.6035]]])
tensor(0.1123)
tensor(0.1123)
tensor(-0.5092)
tensor(-0.5092)


In [28]:
diagonals_list = []
d = 2
w = 4
seq_len = w * d
for j in range(-d * w, d, d):
    # print("j ==", j)
    diagonal_mask = torch.zeros(seq_len, device='cpu', dtype=torch.uint8)
    diagonal_mask[:-j] = 1
    diagonals_list.append(diagonal_mask)
mask = torch.stack(diagonals_list, dim=-1)
print(mask)
print(mask.shape)
mask = mask[None, :, None, :] 
print(mask)
print(mask.shape)
mask = mask.flip(dims=(1, 3)).bool()
print(mask)
print(mask.shape)

tensor([[1, 1, 1, 1, 0],
        [1, 1, 1, 1, 0],
        [1, 1, 1, 0, 0],
        [1, 1, 1, 0, 0],
        [1, 1, 0, 0, 0],
        [1, 1, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0]], dtype=torch.uint8)
torch.Size([8, 5])
tensor([[[[1, 1, 1, 1, 0]],

         [[1, 1, 1, 1, 0]],

         [[1, 1, 1, 0, 0]],

         [[1, 1, 1, 0, 0]],

         [[1, 1, 0, 0, 0]],

         [[1, 1, 0, 0, 0]],

         [[1, 0, 0, 0, 0]],

         [[1, 0, 0, 0, 0]]]], dtype=torch.uint8)
torch.Size([1, 8, 1, 5])
tensor([[[[False, False, False, False,  True]],

         [[False, False, False, False,  True]],

         [[False, False, False,  True,  True]],

         [[False, False, False,  True,  True]],

         [[False, False,  True,  True,  True]],

         [[False, False,  True,  True,  True]],

         [[False,  True,  True,  True,  True]],

         [[False,  True,  True,  True,  True]]]])
torch.Size([1, 8, 1, 5])
