In [2]:
# scatter_nd
import tensorflow as tf

indices = tf.constant([[0], [2]])
updates = tf.constant([[[5, 5, 5, 5], [6, 6, 6, 6],
                        [7, 7, 7, 7], [8, 8, 8, 8]],
                        [[5, 5, 5, 5], [6, 6, 6, 6],
                        [7, 7, 7, 7], [8, 8, 8, 8]]])
shape = tf.constant([4, 4, 4])
scatter = tf.scatter_nd(indices, updates, shape)
print(scatter)

# tile
a = tf.constant([[1,2,3],[4,5,6]], tf.int32)
b = tf.constant([1,2], tf.int32)
print(tf.tile(a, b))

tf.Tensor(
[[[5 5 5 5]
  [6 6 6 6]
  [7 7 7 7]
  [8 8 8 8]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[5 5 5 5]
  [6 6 6 6]
  [7 7 7 7]
  [8 8 8 8]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]], shape=(4, 4, 4), dtype=int32)
tf.Tensor(
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]], shape=(2, 6), dtype=int32)


In [7]:
nums = tf.range(0, limit=10)
# print(nums)
nums = tf.expand_dims(nums, 1)
# print(nums)

extend_vab = tf.constant([
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],  
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]])
# print(extend_vab)

attn_len = tf.shape(extend_vab)[1]
# print(attn_len)

batch_nums = tf.tile(nums, [1, attn_len])
# print(batch_nums)

indices = tf.stack([batch_nums, extend_vab], axis=2)
print(indices)

shape = [10, 4]
# print(indices.shape[:-1] + shape[indices.shape[-1]:])
dists = tf.constant(
        [[[1, 2, 3, 4],
        [2, 3, 4, 5],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

dist = [
        tf.scatter_nd(indices, cp_dist, shape)
        for cp_dist in dists
]
# print(dist)

tf.Tensor(
[[[0 0]
  [0 1]
  [0 2]
  [0 3]]

 [[1 0]
  [1 1]
  [1 2]
  [1 3]]

 [[2 0]
  [2 1]
  [2 2]
  [2 3]]

 [[3 0]
  [3 1]
  [3 2]
  [3 3]]

 [[4 0]
  [4 1]
  [4 2]
  [4 3]]

 [[5 0]
  [5 1]
  [5 2]
  [5 3]]

 [[6 0]
  [6 1]
  [6 2]
  [6 3]]

 [[7 0]
  [7 1]
  [7 2]
  [7 3]]

 [[8 0]
  [8 1]
  [8 2]
  [8 3]]

 [[9 0]
  [9 1]
  [9 2]
  [9 3]]], shape=(10, 4, 2), dtype=int32)


In [35]:
import tensorflow as tf

target = tf.constant([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
batch_nums = tf.range(0, limit=10)

indices = tf.stack((batch_nums, target), axis=1)
print(indices)

dists = tf.constant(
        [[1, 2, 3, 4],
        [2, 1, 4, 5],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]])

gold_probs = tf.gather_nd(dists, indices)
print(gold_probs)

tf.Tensor(
[[0 1]
 [1 1]
 [2 1]
 [3 1]
 [4 1]
 [5 1]
 [6 1]
 [7 1]
 [8 1]
 [9 1]], shape=(10, 2), dtype=int32)
tf.Tensor([2 1 2 2 2 2 2 2 2 2], shape=(10,), dtype=int32)


In [34]:
# tf.gather_nd

import tensorflow as tf

a = tf.Variable([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 10],
                 [11, 12, 13, 14, 15]])
index_a1 = tf.constant([[0, 2], [0, 4], [2, 2]])  # 随便选几个
index_a2 = tf.constant([0, 1])  # 0行1列的元素——2
index_a3 = tf.constant([[0], [1]])  # [第0行,第1行]
index_a4 = tf.constant([0])  # 第0行

print(tf.gather_nd(a, index_a1))
print(tf.gather_nd(a, index_a2))
print(tf.gather_nd(a, index_a3))
print(tf.gather_nd(a, index_a4))

tf.Tensor([ 3  5 13], shape=(3,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(2, 5), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [40]:
x = tf.constant([[1, 1, 0], [1, 1, 1]])
tf.reduce_sum(x)  # 6
tf.reduce_sum(x, 0)  # [2, 2, 2]
tf.reduce_sum(x, 1)  # [3, 3]
# tf.reduce_sum(x, 1, keepdims=True)  # [[3], [3]]
# tf.reduce_sum(x, [0, 1])  # 6

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3])>